config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#index'
  get '/users/newformhtml', to: 'users#newformhtml', as: 'nouvelutilisateurhtml'
  post '/users/newformhtml', to: 'users#createformhtml'

  get '/users/newformtag', to: 'users#newformtag', as: 'nouvelutilisateurformtag'
  post '/new', to: 'users#createformtag', as: 'creationutilisateur'#pour le 2ème formulaire

  get '/users/newformfor', to: 'users#newformfor', as: 'nouvelutilisateurformfor'
  post '/users/newformfor', to: 'users#createformfor'

  get '/users/results', to: 'users#results'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def newformhtml
  end

  def createformhtml
    @user = User.new
    @user.username = params[:username]
    @user.email = params[:email]
    @user.bio = params[:bio]
    @user.save
    redirect_to users_results_path
  end

  def newformtag
    @user = User.new
  end

  def createformtag
    @user = User.new
    @user.username = params[:username]
    @user.email = params[:email]
    @user.bio = params[:bio]
    @user.save
    redirect_to users_results_path
  end

  def newformfor
    @user = User.new
  end
  def createformfor
    @user = User.new
    @user.username = params[:user][:username]
    @user.email = params[:user][:email]
    @user.bio = params[:user][:bio]
    @user.save
    redirect_to users_results_path
  end

  def results
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <title>ILoveForms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">I LOVE FORMS</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=nouvelutilisateurhtml_path%>">Form html</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=nouvelutilisateurformtag_path%>">Form form_tag</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%=nouvelutilisateurformfor_path%>">Form form-for</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>


    <center>
      <%= yield %>
    </center>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>StaticPages#index</h1>
<p>Find me in app/views/static_pages/index.html.erb</p>
Bienvenue sur ma page d'accueil
Pour créer un utilisateur avec le formulaire 1, c'est par ici <a href="<%=nouvelutilisateurhtml_path%>" > cliquez ici</a>
<br>
<br>
Pour créer un utilisateur avec le formulaire form_tag, c'est par ici <a href="<%=nouvelutilisateurformtag_path%>" > cliquez ici</a>
<br>
<br>
Pour créer un utilisateur avec le formulaire form_for, c'est par ici <a href="<%=nouvelutilisateurformfor_path%>" > cliquez ici</a>

app/views/users/newformfor.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/newformfor.html.erb</p>

3) Voici le form_for

<%= form_for @user, url: {action: "createformfor"}, html: {class: "nifty_form"} do |f| %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
    <br>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
    <br>
    <%= f.label :bio %><br />
    <%= f.text_area :bio %>
  </div>

  <div class="actions">
    <%= f.submit "Enregistrer" %>
  </div>

<% end %>

app/views/users/newformhtml.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/newformhtml.html.erb</p>

#1) Voici le formulaire HTML

<form action= "<% creationutilisateur_path%>" method="post">
    <div class="form-group">
        <label for="name">Nom :</label><br>
        <input type="text" id="name" name="username">
    </div>
    <div class="form-group">
        <label for="mail">e-mail :</label><br>
        <input type="email" id="mail" name="email">
    </div>
    <div class="form-group">
        <label for="msg">Racontez-vous :</label><br>
        <textarea id="msg" name="bio"></textarea>
        <br /> <br />
        <input type="submit" value="Submit" class="btn btn-primary">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    </div>
</form>

app/views/users/newformtag.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/newformtag.html.erb</p>

2) Voici le form-tag
<%= form_tag "/new", method: "post" do%>
  <div class="form-group">
    Comment vous appelez-vous ?<br>
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="text" name="username" value="votre prénom">
    <br>
    <br>
    Renseignez votre email :<br>
    <input type="email"  name="email">
    <br>
    Votre bio<br>
    <textarea type="text" name="bio" value="votre nom">
    </textarea><br><br>
    <input type="submit" value="Submit">
  </div>
<%end%>

app/views/users/results.html.erb
<h1>Users#utilisateurs</h1>
<p>Find me in app/views/users/results.html.erb</p>

Bienvenue 